title: This is my blog~
author: Xu Jiang
email: xu.jiang@tufts.com
description: > # this means to ignore newlines until "baseurl:"
  Really exciting to learn this new site for data science~

# social links
twitter_username: CeciiReal # DO NOT include the @ character, or else the build will fail!
github_username:  ceciijjj # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
